<?php
/**
 * Created by PhpStorm.
 * User: niklase
 * Date: 08/11/2016
 * Time: 14.10
 */

namespace GameOfLife\Command;


use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;

class GameOfLifeCommand extends Command
{
    public function fooBar() {

    }

    protected function getEngine() {
        echo 'virhe';
    }

    protected function configure()
    {
        parent::configure(); // TODO: Change the autogenerated stub
    }

    protected function execute(InputInterface $input, OutputInterface $output)
    {
        $engine = $this->getEngine();
        $width = $input->getOption('width') ? $input->getOption('width') : 100;
        $height = $input->getOption('height') ? $input->getOption('height') : 100;
        $seed = $input->getOption('seed');
        $board = $engine->generateBoard($width,$height);
        $board->setSeed($seed);
        $engine->run();
    }
}