<?php
require __DIR__ . '/../vendor/autoload.php';
/**
 * Created by PhpStorm.
 * User: niklase
 * Date: 08/11/2016
 * Time: 13.30
 */
class ApplicationTest extends PHPUnit_Framework_TestCase
{
    public static function setUpBeforeClass()
    {
        parent::setUpBeforeClass(); // TODO: Change the autogenerated stub
        $loader = new \Symfony\Component\ClassLoader\Psr4ClassLoader();
        $loader->addPrefix('GameOfLife', __DIR__ . '/../src');
        $loader->register();
    }

    public function test()
    {
        $application = new \GameOfLife\Application('GAME OF LIFE', '0.1');
        $prophet = new Prophecy\Prophet;
        $gameOfLifeCommand = $prophet->prophesize();
        $gameOfLifeCommand->willExtend('\GameOfLife\Command\GameOfLifeCommand');
        $application->add($gameOfLifeCommand->reveal());
        $gameOfLifeCommand->fooBar()->shouldBeCalled();
        $application->run();
        $prophet->checkPredictions();
    }
}
