<?php
require __DIR__ . '/../vendor/autoload.php';

/**
 * Created by PhpStorm.
 * User: akis
 * Date: 15/11/16
 * Time: 14:22
 */
class GameOfLifeCommandTest extends PHPUnit_Framework_TestCase
{
    private $prophet;

    public static function setUpBeforeClass()
    {
        parent::setUpBeforeClass(); // TODO: Change the autogenerated stub
        $loader = new \Symfony\Component\ClassLoader\Psr4ClassLoader();
        $loader->addPrefix('GameOfLife', __DIR__ . '/../src');
        $loader->addPrefix('Test', __DIR__ );
        $loader->register();
    }

    protected function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->prophet = new Prophecy\Prophet;



    }


    public function test() {
        // Arrange

        $stuff = $this->prophet->prophesize();
        $stuff->willExtend('\GameOfLife\Stuff');
        $stuff->generateBoard(400,100)->shouldBeCalled();

        // Act
        $gameOfLifeCommand = new \Test\GameOfLifeCOmmandStubb($stuff->reveal()
        );
        $input = $this->prophet->prophesize();
        $input->willImplement('\Symfony\Component\Console\Input\InputInterface');

        $output = $this->prophet->prophesize();
        $output->willImplement('\Symfony\Component\Console\Output\OutputInterface');

        $gameOfLifeCommand->testExecute($input->reveal(), $output->reveal());

        // Assert
        $this->prophet->checkPredictions();
    }
}
